package com.dbdivinity.colonel.util;

// This class is autogenerated by Gradle, so we don't have to worry about updating it.
public class ModInfo {
    public static final String id = "colonel";
    public static final String version = "1.0";
    public static final String baseCommand = "tm";
}
